### ISSUE TITLE
[BUG] Error on CLI Execution / Error while extracting

### ISSUE THREAD

**Issue by jshster** [Chris2011/minifierbeans#106] opened 2024-03-27 04:08 UTC
**Search first**
Please make sure, that your issue is not covered by any other ticket. Please search first before you create a ticket.

**Describe the bug**
When saving a file or right clicking and trying to Minify File the IDE reports Error on CLI Execution.  It states 

**To Reproduce**
1. Open .js or .css file, make edit and Save

**Expected behavior**
Should minify the file.  I swear it was minifying the file until a day or a few days ago and then all of a sudden it stopped working. 

**Screenshots**
![image](https://github.com/Chris2011/minifierbeans/assets/8390432/e104c7cd-16d2-415a-b3f2-52b6c7f7cf12)

**Environment (please complete the following information):**
 - OS: Windows 11
 - NetBeans version: 21
 - JDK version 19.0.1
 - MinifierBeans Version: 3.5.0 (downloaded today)

**Additional context**
I found discussion online that suggested manually extracting the custom-packages.zip file manually.   I have done that and it makes no difference.

**Comment by DimArthur** [comment] 2024-03-27 14:28
Looks to be a part of this issue
![image](https://github.com/Chris2011/minifierbeans/assets/62568198/6a5fb2de-faee-45c4-9895-91b49b11394b)

**Comment by DimArthur** [comment] 2024-03-27 15:22
I guess this solution worked for me:
1) install the newest version
2) unzip `\.netbeans\minifierbeans\custom-packages.zip`
3) move all files from `\.netbeans\minifierbeans\custom-packages\custom-packages\` to `\.netbeans\minifierbeans\custom-packages\custom-packages\`
4) restart IDE

**Comment by Chris2011** [comment] 2024-03-27 21:04
@jshster it is already written in the first like:
Search First - Please make sure, that your issue is not covered by any other ticket. Please search first before you create a ticket.

It is already a duplicate of #104 

Workaround is to manually unzip the archive in the given path.

**Closed by Chris2011** 2024-03-27 21:04 UTC
Labels: bug, help wanted, Hacktoberfest

**Comment by Chris2011** [comment] 2024-03-27 21:12
I updated the custom-packages.zip which has kjust the files inside. The path needs to be .netbeasn/minifierbeans/custom-packages/*.*. Please test it.

**Comment by Chris2011** [comment] 2024-04-02 20:56
So all in all, the first problem was, that I zipped the archive with a wrong compression strength. I just used windows zipping, before I used 7z with highest compression strength (9 - Ultra). The second problem was, that I removed the custom-packages folder from the zip and added the files to the root path which is wrong.

This is fixed in custom-packages 1.5.2 and it should work now out of the box, after opening NetBeans. If not, please empty the folder .netbeans/minifierbeans and restart NetBeans.

With Minifierbeans 3.5.1 I also increased the performance of extracting the archive.
