### ISSUE TITLE
Exception in minifying JS in NB 12.3 and 12.4

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Chris2011/minifierbeans#70] opened 2021-03-26 11:02 UTC
After save or "MinifyJS" command I have this exception:
`java.lang.NullPointerException
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.jsMinify(JSMinify.java:124)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.access$000(JSMinify.java:54)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify$1.run(JSMinify.java:72)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)`
Can you fix it, please, I used to use  your extension. Thanks

**Comment by Chris2011** [comment] 2021-03-26 11:09
Hi,

I need more information please. Which version of the Plugin you use, exact steps to reproduce, everythine what it needs to help me. Also a little reproducable script. Thx :)

**Comment by Ilya-Zhulin** [comment] 2021-03-26 12:00
Hi.
Plugin version 3.3, downloaded from here today. NB 12.3 also installed yesterday. I've just installed Netbeans, plugins and started to work. Experimentally I see, that all minifying command lead to exception. I can only copy as minified from context menu - this works only.

**Comment by Chris2011** [comment] 2021-03-26 12:47
I need all steps that you did :). No need for special steps but did you do a right click on a file? Or did you do a save on that or what exactly? I can't guess.

 > Experimentally I see, that all minifying command lead to exception
How was your experiment? What did you do? Tell me all what I need to reproduce it.

**Comment by Ilya-Zhulin** [comment] 2021-03-27 07:03
Hello. Please, watch this https://yadi.sk/d/C8zIo33aT5eSog screen video. I also showed that checkbox "Minify on Save" doesn't keep its state.

**Comment by Ilya-Zhulin** [comment] 2021-03-30 10:39
Hi
Do you have enough informarion?

**Comment by Chris2011** [comment] 2021-03-31 10:07
Hey thx for asking again. I didn't find time to check this. I will do it in the next couple of days. Thx for your patience :).

**Comment by Chris2011** [comment] 2021-04-06 14:48
Unfortunately, I can't reproduce this problem. You are under windows I see, which JDK do you use?

**Comment by Ilya-Zhulin** [comment] 2021-04-06 15:31
it was JDK14, but after I had this issue, I downloaded JDK 16. Portable version.
I see, this is my only trouble..

**Comment by Chris2011** [comment] 2021-04-07 07:43
So it didn't work with JDK 14 but it worked with 16, right? Or you have the problem on both JDKs? Can you please try to use JDK 11? I will try JDK 14 too to see whether this is the problem or not. Thx for the infos.

**Comment by Chris2011** [comment] 2021-04-19 08:25
Hey @Ilya-Zhulin I didn't try JDK 14 yet. I know that 16 is not supported with 12.3 but it will comes in 12.4. Can you try please different JDKs too like JDK 9, 10 or 11? I really want to help you, but as you can see I can't reproduce the problem. So I need more information.

**Comment by JuergenLaas** [comment] 2021-05-05 12:28
Hello, i want to install Minifierbeans-3.3.0.nbm on Netbeans 12.3 i use last OpenJDK 11 and get an error: 
**netbeans error cannot decrease processed work unit count(-2011422090) to lower value than before (0)** 

What happen?

**Comment by Chris2011** [comment] 2021-05-05 19:58
Hey @JuergenLaas please create a new ticket with all the information and the whole stracktrace. Otherwise I can't help without any information. Thx.

**Comment by Chris2011** [comment] 2021-05-06 08:11
@Ilya-Zhulin did you try Oracle JDK 14 or Open JDK 14?

**Comment by Ilya-Zhulin** [comment] 2021-05-10 21:24
I use Oracle JDK

**Comment by Ilya-Zhulin** [comment] 2021-06-04 09:33
I've updated NB to version 12.4 and now this error looks like this:
`java.lang.NullPointerException: Cannot invoke "java.util.concurrent.Future.get(long, java.util.concurrent.TimeUnit)" because "task" is null
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.jsMinify(JSMinify.java:124)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.access$000(JSMinify.java:54)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify$1.run(JSMinify.java:72)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

**Comment by Chris2011** [comment] 2021-06-04 10:49
Still with Oracle JDK 14?

**Comment by Ilya-Zhulin** [comment] 2021-06-21 07:23
Hi. Now I've downloaded previous major version - Oracle jdk-11.0.11 and have the same problem:
```java.lang.NullPointerException
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.jsMinify(JSMinify.java:124)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify.access$000(JSMinify.java:54)
	at io.github.chris2011.netbeans.minifierbeans.javascript.JSMinify$1.run(JSMinify.java:72)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by Chris2011** [comment] 2021-06-21 10:19
Why did you close the ticket? Is it working now? If not, i guess you have Windows, right? Can you check whether the folder in your user path exists or not: users\username\.netbeans\minifierbeans\custom-packages with a node_modules folder and some scripts?

**Comment by Ilya-Zhulin** [comment] 2021-06-21 11:28
Sorry with closing - my bad. There is this folder on the screenshot. I see a package in zip archive (on the left panel), but folder contains json file only (shown on the right panel)
![image](https://user-images.githubusercontent.com/4967754/122754863-d8440680-d29c-11eb-9a45-3e7da912dffd.png)

**Comment by Ilya-Zhulin** [comment] 2021-06-21 11:54
OK, it's working now. I unpacked this archive, started NetBeans. The program started to download and unpack a new minifyneans archive, but it was finished by error of unpacking. I tried twice but with the same result. After this I found that custom_packages.zip become 36 Mb instead of 5. I unpacked it by hand and started NB again. It works from that.

**Comment by Ilya-Zhulin** [comment] 2021-06-21 11:57
Only moment - NB doesn't store Minify on save checkbox for all tabs - CSS, JS etc. It is unchecked every time after restart of NB. Do you know something about it?

**Comment by Chris2011** [comment] 2021-06-21 16:33
> Only moment - NB doesn't store Minify on save checkbox for all tabs - CSS, JS etc. It is unchecked every time after restart of NB. Do you know something about it?
> ![image](https://user-images.githubusercontent.com/4967754/122758043-03305980-d2a1-11eb-9a09-ceb34d8d82c9.png)

Please see the issue section first, I already created it #73.



> OK, it's working now. I unpacked this archive, started NetBeans. The program started to download and unpack a new minifyneans archive, but it was finished by error of unpacking. I tried twice but with the same result. After this I found that custom_packages.zip become 36 Mb instead of 5. I unpacked it by hand and started NB again. It works from that.

Can you please have a look, what the error was? If I don't show it, please have a look into the ide.log file.

So the original NPE was the error of missing CLIs I will handle this, by showing a notification, check them and to trigger the download/unpacking again. But if there is a problem while unpacking, I need to know what the problem is. Thx.

**Comment by Ilya-Zhulin** [comment] 2021-06-22 11:14
This one (if I think correct )
```
INFO [org.netbeans.modules.progress.spi.InternalHandle]: Cannot process more work than scheduled. Progress handle with name "Extracting minifierbeans archive" has requested progress to workunit no.745547391 but the total number of workunits is 0. That means the progress bar UI will not display real progress and will stay at 100%.
java.lang.IllegalArgumentException
[catch] at org.netbeans.modules.progress.spi.InternalHandle.progress(InternalHandle.java:329)
	at org.netbeans.api.progress.ProgressHandle.progress(ProgressHandle.java:264)
	at org.netbeans.api.progress.ProgressHandle.progress(ProgressHandle.java:242)
	at io.github.chris2011.netbeans.minifierbeans.Installer.extractArchive(Installer.java:229)
	at io.github.chris2011.netbeans.minifierbeans.Installer.access$400(Installer.java:33)
	at io.github.chris2011.netbeans.minifierbeans.Installer$2.run(Installer.java:164)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by Chris2011** [comment] 2021-06-22 11:29
Thx, will have a look :)

**Comment by Chris2011** [comment] 2021-07-07 20:20
Fixed in release 3.3.1, please test it @Ilya-Zhulin.

**Comment by Chris2011** [comment] 2021-07-07 20:20
The problem was, that I didn't know how the Progressbar in NetBeans worked but now I handled it.

**Closed by Chris2011** 2021-07-07 20:20 UTC
Labels: High, bug, work-in-progress

**Comment by Ilya-Zhulin** [comment] 2021-07-19 13:04
Hi, problem with exception is solved. Sorry for delay - it was vacation. Thank you.

**Comment by Chris2011** [comment] 2021-07-19 13:47
No problem :). Thx for the info.
